### PR TITLE
Riverdale.

### PR DESCRIPTION
**Pull request by Phelickz**
View Questions done.
Edit Questions done.
Correct answer bug fixed.

### CODE REVIEW

**Comment by HenryEffiong** [comment]
smallville, riverdale... what next, papa ajasco?

**Comment by Phelickz** [comment]
Lmao😂😂😂

**Comment by WanjiruCate** [comment]
Today it's not resurection :rofl: :rofl:

**Comment by Phelickz** [comment]
We can't resurrect twice na😂😂

**Pull request merged**
